on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: modify manifest.json & package.json version
        run: |
          # Remove 'v' from github.ref_name and store it in a variable
          version=$(echo "${{ github.ref_name }}" | sed 's/^v//')

          # Update manifest.json version
          echo "$(jq --arg version "$version" '.version=$version' manifest.json)" > manifest.json

          # Update package.json version
          echo "$(jq --arg version "$version" '.version=$version' package.json)" > package.json

      - name: Build
        run: pnpm run build

      - name: Compress dist
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r Translator-${{ github.ref_name }}.zip dist

      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          name: Translator ${{ github.ref_name }}
          files: Translator-${{ github.ref_name }}.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}